# Generated by Django 5.0.6 on 2024-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_data', models.DateField()),
                ('event_description', models.TextField(max_length=1000)),
                ('your_name', models.CharField(max_length=30)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_phone', models.IntegerField(max_length=10)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('other', 'Other')], max_length=20)),
                ('event_time', models.TimeField()),
            ],
        ),
    ]
