# Generated by Django 5.0.7 on 2024-07-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizeevent',
            name='your_phone',
            field=models.IntegerField(),
        ),
    ]
