# Generated by Django 5.0.7 on 2024-07-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_organizeevent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizeevent',
            old_name='event_data',
            new_name='event_date',
        ),
    ]
