# Generated by Django 5.0.7 on 2024-07-27 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_event_data_organizeevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizeevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
