# Generated by Django 5.0.7 on 2024-07-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_organizeevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizeevent',
            name='location',
            field=models.CharField(default='Kathmandu', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizeevent',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('meet and greet', 'Meet and Greet'), ('other', 'Other')], max_length=20),
        ),
    ]
